apiVersion: v2
name: prerender
description: Helm chart for prerender wrapping tvanro/prerender-alpine
type: application
version: 1.0.2
appVersion: 6.3.0
home: https://github.com/prerender/prerender
keywords:
  - prerender
  - render
  - chrome
  - headless-chrome
  - tvanro
sources:
  - https://github.com/prerender/prerender
  - https://github.com/tvanro/prerender-alpine
  - https://github.com/utkuozdemir/helm-charts
icon: https://utkuozdemir.org/helm-charts/prerender.png
maintainers:
  - name: Utku Özdemir
    email: uoz@protonmail.com
    url: https://utkuozdemir.org
annotations:
  artifacthub.io/license: MIT
  artifacthub.io/changes: |
    - Fixes on README
  artifacthub.io/images: |
    - name: tvanro/prerender-alpine
      image: docker.io/tvanro/prerender-alpine:6.2.0
