apiVersion: v2
name: filebrowser
description: A Helm chart for the File Browser project
type: application
version: 0.1.3
appVersion: v2.16.0
home: https://filebrowser.org
keywords:
  - filebrowser
  - file-browser
  - file-server
  - http-file-server
sources:
  - https://github.com/filebrowser/filebrowser
  - https://github.com/utkuozdemir/helm-charts
icon: https://utkuozdemir.org/helm-charts/filebrowser.png
maintainers:
  - name: Utku Özdemir
    email: uoz@protonmail.com
    url: https://utkuozdemir.org
annotations:
  artifacthub.io/license: MIT
  artifacthub.io/changes: |
    - Fix storage class name on DB pvc
  artifacthub.io/images: |
    - name: filebrowser/filebrowser
      image: docker.io/filebrowser/filebrowser:v2.16.0
