apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "transmission-openvpn.fullname" . }}
  labels:
    {{- include "transmission-openvpn.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.env | nindent 2 }}
