apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "transmission-openvpn.fullname" . }}
  labels:
{{ include "transmission-openvpn.labels" . | indent 4 }}
data:
  CREATE_TUN_DEVICE: "true"
  LOCAL_NETWORK: {{ .Values.localNetworkCidr }}
  OPENVPN_PROVIDER: CUSTOM
  OPENVPN_USERNAME: ignored
  OPENVPN_PASSWORD: ignored
  TRANSMISSION_PEER_PORT: "{{ .Values.peerPort }}"
{{- if .Values.customWebUi.enabled }}
  TRANSMISSION_WEB_UI: {{ .Values.customWebUi.interface }}
{{- end }}
{{- with .Values.customEnvVars }}
{{- toYaml . | nindent 2 }}
{{- end }}
