apiVersion: v1
kind: Secret
metadata:
  name: {{ include "transmission-openvpn.fullname" . }}
  labels:
    {{- include "transmission-openvpn.labels" . | nindent 4 }}
data:
  {{- range $k, $v := .Values.secretEnv }}
  {{ $k }}: {{ $v | b64enc }}
  {{- end }}
