apiVersion: v1
metadata:
  name: {{ include "transmission-openvpn.fullname" . }}
  labels:
{{ include "transmission-openvpn.labels" . | indent 4 }}
data:
  default.ovpn: {{ b64enc .Values.openvpnConfig }}
kind: Secret
type: Opaque
