apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "plex.fullname" . }}
  labels:
{{ include "plex.labels" . | indent 4 }}
data:
  TZ: {{ .Values.timezone }}
  HOSTNAME: {{ .Values.hostname }}
