{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "nvidia-gpu-exporter.fullname" . }}
  labels: {{ include "nvidia-gpu-exporter.labels" . | indent 4 }}
  {{- if .Values.serviceMonitor.additionalLabels }}
{{ toYaml .Values.serviceMonitor.additionalLabels | indent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      app: {{ template "nvidia-gpu-exporter.name" . }}
      release: {{ .Release.Name }}
  endpoints:
    - port: metrics
      scheme: {{ .Values.serviceMonitor.scheme }}
      {{- if .Values.serviceMonitor.bearerTokenFile }}
      bearerTokenFile: {{ .Values.serviceMonitor.bearerTokenFile }}
      {{- end }}
      {{- if .Values.serviceMonitor.tlsConfig }}
      tlsConfig: {{ toYaml .Values.serviceMonitor.tlsConfig | nindent 8 }}
      {{- end }}
      {{- if .Values.serviceMonitor.proxyUrl }}
      proxyUrl: {{ .Values.serviceMonitor.proxyUrl}}
      {{- end }}
      {{- if .Values.serviceMonitor.scrapeTimeout }}
      scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
      {{- end }}
{{- if .Values.serviceMonitor.relabelings }}
      relabelings:
{{ toYaml .Values.serviceMonitor.relabelings | indent 6 }}
{{- end }}
{{- end }}
