apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "prerender.fullname" . }}
  labels:
    {{- include "prerender.labels" . | nindent 4 }}
data:
{{- range $k, $v := .Values.env }}
  {{ $k }}: {{ $v | quote }}
{{- end }}
