apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "transmission-openvpn.fullname" . }}
  labels:
    {{- include "transmission-openvpn.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "transmission-openvpn.fullname" . }}
  selector:
    matchLabels:
      {{- include "transmission-openvpn.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "transmission-openvpn.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "transmission-openvpn.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 9091
              protocol: TCP
            - name: peer
              containerPort: {{ .Values.peerPort }}
          readinessProbe:
            httpGet:
              path: /
              port: http
          volumeMounts:
            - mountPath: /dev/net/tun
              name: dev-net-tun
            - mountPath: /data
              name: data
          envFrom:
            - configMapRef:
                name: {{ include "transmission-openvpn.fullname" . }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
        - hostPath:
            path: /dev/net/tun
            type: CharDevice
          name: dev-net-tun
{{- if and .Values.persistence.enabled .Values.persistence.existingClaim }}
        - name: data
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim }}
{{- else if not .Values.persistence.enabled }}
        - name: data
          emptyDir: {}
{{- end }}
  volumeClaimTemplates:
{{- if and .Values.persistence.enabled (not .Values.persistence.existingClaim) }}
    - metadata:
        name: data
        labels:
          app: "{{ template "transmission-openvpn.name" . }}"
          release: {{ .Release.Name | quote }}
          heritage: {{ .Release.Service | quote }}
      spec:
        accessModes:
        {{- range .Values.persistence.accessModes }}
          - {{ . | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.persistence.size | quote }}
        {{ include "transmission-openvpn.storageClass" . }}
{{- end }}