# Default values for transmission-openvpn.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: haugene/transmission-openvpn
  tag: 2.10-alpine
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
  # kubernetes.io/tls-acme: "true"
  labels: {}
  path: /
  hosts:
    - chart-example.local
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

## Enable persistence using Persistent Volume Claims
## ref: http://kubernetes.io/docs/user-guide/persistent-volumes/
##
persistence:
  enabled: true
  # storageClassName: default
  accessModes:
    - ReadWriteOnce
  size: 32Gi
  annotations:
     "helm.sh/resource-policy": keep
  finalizers:
    - kubernetes.io/pvc-protection
  # subPath: ""
  # existingClaim:

localNetworkCidr: 10.217.0.0/16

#openvpnConfig: |
#  client
#  dev tun
#  remote ...
#  ...
#  key-direction 1
#  <ca>
#  ...
#  </ca>
#  <cert>
#  ...
#  </cert>
#  <key>
#  ...
#  </key>
#  <tls-auth>
#  ...
#  </tls-auth>


# see: https://haugene.github.io/docker-transmission-openvpn/arguments/#alternative_web_uis
customWebUi:
  enabled: true
  interface: kettu

peerPort: 51413

# see: https://haugene.github.io/docker-transmission-openvpn/arguments/#transmission_configuration_options
# config reference: https://github.com/transmission/transmission/wiki/Editing-Configuration-Files
customEnvVars: {}
#  TRANSMISSION_DOWNLOAD_DIR: "/data/downloads"
#  TRANSMISSION_START_ADDED_TORRENTS: "false"
