apiVersion: v2
name: nvidia-gpu-exporter
description: Nvidia GPU exporter for prometheus using nvidia-smi binary to gather metrics.
type: application
version: 1.0.0
appVersion: 1.2.1
home: https://github.com/utkuozdemir/nvidia_gpu_exporter
keywords:
  - nvidia
  - gpu
  - exporter
  - nvidia-smi
  - nvidia-gpu-exporter
  - prometheus
sources:
  - https://github.com/utkuozdemir/helm-charts
icon: https://utkuozdemir.org/helm-charts/nvidia.png
maintainers:
  - name: Utku Özdemir
    email: utkuozdemir@gmail.com
    url: https://utkuozdemir.org
annotations:
  artifacthub.io/license: MIT
  artifacthub.io/changes: |
    - Add hostNetwork to the DS and make svc opt-out
    - Bump appVersion to 1.2.1
    - Release 1.0.0 of the chart
  artifacthub.io/images: |
    - name: utkuozdemir/nvidia_gpu_exporter
      image: docker.io/utkuozdemir/nvidia_gpu_exporter:1.2.1
