apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "transmission-exporter.fullname" . }}
  labels:
{{ include "transmission-exporter.labels" . | indent 4 }}
data:
  WEB_PATH: "{{ .Values.web.path }}"
  WEB_ADDR: "{{ .Values.web.addr }}"
  TRANSMISSION_ADDR: "{{ .Values.transmission.addr }}"
