apiVersion: v1
metadata:
  name: {{ include "transmission-exporter.fullname" . }}
  labels:
{{ include "transmission-exporter.labels" . | indent 4 }}
stringData:
  {{- with .Values.transmission.username }}
  TRANSMISSION_USERNAME: {{ . | quote }}
  {{- end }}
  {{- with .Values.transmission.password }}
  TRANSMISSION_PASSWORD: {{ . | quote }}
  {{- end }}
kind: Secret
type: Opaque
