{{- if .Values.transmission.authentication.enabled -}}
apiVersion: v1
metadata:
  name: {{ include "transmission-exporter.fullname" . }}
  labels:
{{ include "transmission-exporter.labels" . | indent 4 }}
data:
  TRANSMISSION_USERNAME: "{{ .Values.transmission.username | b64enc }}"
  TRANSMISSION_PASSWORD: "{{ .Values.transmission.password | b64enc }}"
kind: Secret
type: Opaque
{{- end }}
