apiVersion: v1
kind: Service
metadata:
  name: {{ include "transmission-exporter.fullname" . }}
  labels:
{{ include "transmission-exporter.labels" . | indent 4 }}
{{- if .Values.service.annotations }}
  annotations:
  {{- range $key, $value := .Values.service.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    app.kubernetes.io/name: {{ include "transmission-exporter.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
