apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dontstarvetogether.fullname" . }}-mods
data:
{{- if not (empty .Values.config.mods.additionalFiles) -}}
{{- toYaml .Values.config.mods.additionalFiles | nindent 2 }}
{{- end }}