{{- if .Values.podSecurityPolicy.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "dontstarvetogether.fullname" . }}
  labels:
    {{- include "dontstarvetogether.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - {{ template "podSecurityPolicy.apiGroup" . }}
    resources:
      - podsecuritypolicies
    verbs:
      - use
    resourceNames:
      - {{ include "dontstarvetogether.fullname" . }}
{{- end }}
