apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dontstarvetogether.fullname" . }}-root
  labels:
    {{- include "dontstarvetogether.labels" . | nindent 4 }}
stringData:
{{- if not (empty .Values.config.root.additionalFiles) -}}
{{- toYaml .Values.config.root.additionalFiles | nindent 2 }}
{{- end }}
  cluster_token.txt: {{ required "config.root.clusterToken is required!" .Values.config.root.clusterToken }}
  cluster.ini: |
    [NETWORK]
    {{- range $key, $value := .Values.config.root.network }}
    {{- if and (eq $key "cluster_password") (empty $value) }}
    {{ $key }} = {{ randAlphaNum 16 }}
    {{- else }}
    {{ $key }} = {{ $value }}
    {{- end }}
    {{- end }}

    [GAMEPLAY]
    {{- range $key, $value := .Values.config.root.gameplay }}
    {{ $key }} = {{ $value }}
    {{- end }}

    [STEAM]
    {{- range $key, $value := .Values.config.root.steam }}
    {{ $key }} = {{ $value }}
    {{- end }}

    [MISC]
    {{- range $key, $value := .Values.config.root.misc }}
    {{ $key }} = {{ $value }}
    {{- end }}

    [SHARD]
    {{- range $key, $value := .Values.config.root.shard }}
    {{ $key }} = {{ $value }}
    {{- end }}
