{{- if or .Values.serviceAccount.create .Values.podSecurityPolicy.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "dontstarvetogether.serviceAccountName" . }}
  labels:
    {{- include "dontstarvetogether.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
