apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "huginn.fullname" . }}
  labels:
    {{- include "huginn.labels" . | nindent 4 }}
data:
  {{- if not .Values.seed.enabled }}
  DO_NOT_SEED: "true"
  {{- end }}
  HUGINN_DATABASE_ADAPTER: mysql2
  HUGINN_DATABASE_NAME: {{ .Values.mysql.auth.database | quote }}
  HUGINN_DATABASE_HOST: {{ include "huginn.fullname" . }}-mysql
  HUGINN_DATABASE_PORT: {{ .Values.mysql.primary.service.port | quote }}
  HUGINN_PORT: {{ .Values.web.port | quote }}
