apiVersion: v1
kind: Secret
metadata:
  name: {{ include "huginn.fullname" . }}
  labels:
    {{- include "huginn.labels" . | nindent 4 }}
data:
  HUGINN_SEED_USERNAME: {{ .Values.seed.username | b64enc | quote }}
  HUGINN_SEED_PASSWORD: {{ .Values.seed.password | b64enc | quote }}
  HUGINN_DATABASE_USERNAME: {{ .Values.mysql.auth.username | b64enc | quote }}
  HUGINN_DATABASE_PASSWORD: {{ .Values.mysql.auth.password | b64enc | quote }}
